version: '3.7'
services:
  frontend:
    build: 
      context: .
      target: "dev"
    image: "erasme/gestion_inventaire:dev"
    volumes:
      - ./src/:/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env