version: '3.7'
services:
  traefik:
    image: "traefik:v2.5"  # Use the version of Traefik you prefer
    container_name: gestion-inventaire-traefik
    command:
      - "--api.insecure=true"  # Enable insecure API on port 8080 (for testing purposes)
      - "--providers.docker=true"  # Enable Docker provider
      - "--entrypoints.web.address=:80"  # HTTP entry point
      - "--entrypoints.websecure.address=:443"  # HTTPS entry point
    ports:
     # - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Connect to Docker socket

  frontend:
    container_name: gestion-inventaire-frontend
    build:
      context: .
      target: "dev"
    image: "erasme/gestion_inventaire:dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"  # Use your localhost domain
      - "traefik.http.routers.frontend.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.frontend.tls=true"  # Enable TLS
    volumes:
      - ./src/:/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env
